# Generated by Django 5.0.6 on 2024-05-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_producto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Comics',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Libro',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RenameField(
            model_name='comics',
            old_name='apellido',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='apellido',
            new_name='autor',
        ),
    ]
