# Generated by Django 5.0.6 on 2024-06-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_vinilo_rename_cliente_comics_rename_usuario_libro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinilo',
            old_name='banda',
            new_name='artista',
        ),
    ]
