# Generated by Django 4.2.13 on 2024-06-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='code',
            field=models.CharField(default='CREATED', max_length=10),
        ),
    ]
