# Generated by Django 4.2.13 on 2024-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='default/avatar.jpg', upload_to='upload/customer/'),
        ),
    ]
